### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode 

### ISSUE THREAD

**Issue by zhbzhbzhbz** [boppreh/replace_me#1]
Very useful library~ I just had to edit a variable.
And learned the usage of "getframeinfo(stack()[1][0])"

```
  File "D:\Program Files\Python38\lib\site-packages\replace_me.py", line 52, in replace_me
    lines = f.read().split('\n')
UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 10: illegal multibyte sequence
```

**Comment by boppreh** [comment]
Thanks, I've added an explicit encoding when reading the file so it doesn't depend on your locale. This assumes Python files are in UTF-8, but really, you should not be using anything else.

Give the new version a try.
